# O comando FROM serve para definir a partir de qual imagem base estamos criando a 
# nossa imagem customizada
FROM nginx:1.25-alpine

# O comando COPY copia todos os arquivos dentro do diretorio web na pasta raiz deste projeto
# para a pasta /usr/share/nginx/html
COPY web /usr/share/nginx/html