version: '3.7'

services:
  web:
    image: nginx:1.25-alpine
    container_name: workshop.web
    ports:
      - "8080:80"

  # web:
  #   image: nginx:1.25-alpine
  #   container_name: workshop.web
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - ./web:/usr/share/nginx/html

  # web:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: workshop.web
  #   ports:
  #     - "8080:80"